# -- Override full name
fullnameOverride: ""
# -- Override name
nameOverride: ""

# -- Replica count
replicaCount: 1
image:
  # -- Image repository
  repository: ghcr.io/sap/project-operator
  # -- Image tag (defauls to .Chart.AppVersion)
  tag: ""
  # -- Image pull policy
  pullPolicy: IfNotPresent
# -- Image pull secrets
imagePullSecrets: []
# -- Node selector
nodeSelector: {}
# -- Affinity settings
affinity: {}
# -- Topology spread constraints (if unspecified, default constraints for hostname and zone will be generated)
topologySpreadConstraints: []
# -- Default topology spread policy for hostname
defaultHostNameSpreadPolicy: ScheduleAnyway
# -- Default topology spread policy for zone
defaultZoneSpreadPolicy: ScheduleAnyway
# -- Tolerations
tolerations: []
# -- Priority class
priorityClassName: ""
# -- Pod security context
podSecurityContext: {}
# -- Additional pod annotations
podAnnotations: {}
# -- Additional pod labels
podLabels: {}
# -- Container security context
securityContext: {}
resources:
  limits:
    # -- Memory limit
    memory: 200Mi
    # -- CPU limit
    cpu: 0.1
  requests:
    # -- Memory request
    memory: 20Mi
    # -- CPU request
    cpu: 0.01
pdb:
  # -- Whether to create a PodDisruptionBudget for the webhook
  enabled: true
  # -- Labels to set on the PodDisruptionBudget
  labels: {}
  # -- Annotations to set on the PodDisruptionBudget
  annotations: {}
  # -- Number of pods that are available after eviction as number or percentage (e.g. 50%)
  # @default -- `"1"` (defaults to 1 if not specified)
  minAvailable: "1"
  # -- Number of pods that are unavailable after eviction as number or percentage (e.g: 50%); has higher precedence over `pdb.minAvailable`
  maxUnavailable: ""
webhook:
  certManager:
    # -- Whether to use cert-manager to manage webhook tls
    enabled: false
    # -- Issuer group (only relevant if enabled is true; if unset, the default cert-manager group is used)
    issuerGroup: ""
    # -- Issuer kind (only relevant if enabled is true; if unset, the default cert-manager type 'Issuer' is used)
    issuerKind: ""
    # -- Issuer name (only relevant if enabled is true; if unset, a self-signed issuer is used)
    issuerName: ""
    
# -- Prefix for project namespaces (if empty, the operator default will be used)
namespacePrefix: ""
# -- Cluster role to be granted to admin members on the project namespace (if empty, the operator default will be used)
adminClusterRole: ""
# -- Cluster role to be granted to viewer members on the project namespace (if empty, the operator default will be used)
viewerClusterRole: ""
# -- Automatically grant cluster view privileges to all members of the project
enableClusterView: false
metrics:
  podMonitor:
    # -- Whether to create a PodMonitor resource
    enabled: false
  prometheusRule:
    # -- Whether to create a PrometheusRule resource
    enabled: false
    # -- PrometheusRule rules
    rules: []